development:
  url: https://localhost:4000
  fathom_site_id: XXXXXX

staging:
  url: https://staging.bagusaji.dev
  fathom_site_id: XXXXXX

production:
  url: https://bagusaji.dev
  fathom_site_id: XXXXXX

previewify_site_id: 755

# TODO: Move to config/initializers.rb.
collections:
  projects:
    output: true
  snippets:
    output: false

# TODO: Move to config/initializers.rb.
feed:
  collections:
    projects: 
      path: /projects.xml
