development:
  url: https://localhost:4000
  fathom_site_id: XXXXXX

staging:
  url: https://staging.bagusaji.dev
  fathom_site_id: XXXXXX

production:
  url: https://bagusaji.dev
  fathom_site_id: XXXXXX

previewify_site_id: 755

# TODO: Move to config/initializers.rb.
collections:
  snippets:
    output: false

# TODO: Move to config/initializers.rb.
feed:
  collections:

# TODO: Categories, tags, or custom taxonomies for turbo-ios series.
# https://www.bridgetownrb.com/docs/resources#taxonomies
